---
- name: "Download filebeat's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb"
    dest: "files/filebeat-{{ filebeat_version }}-amd64.deb"
    validate_certs: false
  register: download_filebeat
  until: download_filebeat is succeeded
  delegate_to: localhost
- name: Copy filebeat to remote host
  copy:
    scr: "files/filebeat-{{ filebeat_version }}-amd64.deb"
    mode: 0755
    dest: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"