---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos7
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    box: bento/centos-7
  - name: ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    box: bento/ubuntu-20.04
provisioner:
  name: ansible
verifier:
  name: ansible
